### ISSUE TITLE
Able to like and dislike comments without logging in

### ISSUE THREAD

**Issue by shvamabps** [lockedandlifted/my4x4#280]
![Screenshot 2023-09-15 171139](https://github.com/lockedandlifted/my4x4/assets/37547983/4c13918e-32de-487d-a57b-d6f86371dd40)
![Screenshot 2023-09-15 171204](https://github.com/lockedandlifted/my4x4/assets/37547983/93c19400-3598-4f44-ae57-36324b36242e)
![Screenshot 2023-09-15 171221](https://github.com/lockedandlifted/my4x4/assets/37547983/79a47937-3a83-4473-b8cf-86ec111eb258)

Also when I click the reply button, it creates an invisible div but not the input section.

**Comment by kengreeff** [comment]
Thank you - fixed in #283
